### PR TITLE
Don't render Markdown when attempting to navigate above first cell

### LINKED ISSUE #52: Navigating above the first cell in vim mode loses focus, if the first cell is a Markdown cell
## Description

Navigating up through cells using 'k', you scroll through code cells line by line and as you pass through markdown cells they're displayed as markdown and then rendered again upon exit. Continuing upwards "above" the first cell loses keyboard focus for the notebook, forcing you to click back on the notebook area with the mouse.

## Reproduce

1. Position cursor near top of notebook
2. Make sure you're in vim mode (hitting 'enter' if need be)
3. Scroll up using 'k'
4. Hit 'k' again after reaching the first cell. Any further keyboard navigation is lost.

## Expected behavior

The 'j' key should continue to work as before, so although 'k' has nowhere further to go, you're at "the top" of the file and 'j' should still work to go back down.

## Context

I don't think anything else is relevant. It's a fresh install from anaconda to jupyterlab_vim version 0.14.5 with Python 3.8.11.

But I would like to add that I think this extension will allow me to migrate from jupyter notebook to jupyter lab.
The keymap summary in the GitHub README is **super** helpful - thank you.
Of course there are new keymaps to use, and half the point of using a vim keymapping is to use 30 years of muscle memory(!) but the basic navigation seems to make sense and it's definitely something I'll be trying to get familiar with. There are definitely behaviours of it that I'm liking, and that I struggled to find how to do using the jupyter notebook vim keymap.
(I find the ctrl-[1, 2, 3] a little unintuitive, but easy enough to toggle through by trial and error).

### PR DESCRIPTION
**Pull request by firai**
Fixes #52. Disable Markdown rendering when the following keys are pressed in the first cell (if it is a Markdown cell), in order to keep CM focused:

- [x] <kbd>Ctrl+k</kbd>
- [x] <kbd>k</kbd>

### CODE REVIEW

**Comment by firai** [comment]
This PR currently makes `activateCellVim()` pass the `activeCellIndex` from the `INotebookTracker` into `modifyCell()`, which in turn passes it into `_modifyEdgeNavigation()`. As far as I can find from the JL API docs, this is not otherwise available in the `activeCell` `ICellModel` currently passed to `modifyCell()`.

In lieu of passing the numerical cell index, it would be possible to make the caller pass a string or enum to identify first and last cells, with `modifyCell()` handling the identification (a dummy/other value would most likely be passed for any other cell location in these cases). This has the advantage of being able to identify the last cell, which may be needed for future special last cell handling (say, if we wanted to auto-return to vim mode after coming back up from the footer after https://github.com/jupyterlab/jupyterlab/pull/14796). I'm not sure if there are any advantages to having the actual cell index. It's also possible to have both if we make `modifyCell()` change the passed cell index to -1 for the last cell, but that's, well, hacky.

**Comment by krassowski** [comment]
>  the cell index is not otherwise available in the `activeCell` `ICellModel` currently passed to `modifyCell()`

This is correct.

> The disadvantage of doing this is that we still don't have a way to identify the last cell

(this can be taken from `.widgets.length`)

>  we make the calling function change the passed cell index to -1 for the last cell

`-1` is already used to indicate no cells in notebook, see [here](https://github.com/jupyterlab/jupyterlab/blob/0b33a5ca9318d909233914adb0cbd90d3bc7a472/packages/notebook/src/widget.ts#L1386-L1391) (though this is implementation detail).

> In lieu of passing the numerical cell index, it would be possible to make the caller pass a string or enum to identify first and last cells, with the calling function handling the identification.

Edge case: console. In console mode there is one cell that can be focused, the input cell at the bottom. There are cells above it which cannot be navigated to. Does it make the input cell the first and the last cell? While console is not currently vim enabled (I think?), it could be in the future.

I think the most future proof approach would be to make `modifyCell` receive two arguments:
- `activeCell` (as it does currently)
- `context: ICellContext` - this will allow to add/remove optional arguments in the future without worrying about argument index in calls; it could be defined as:

```js
interface ICellContext {
  index?: number;
  cellCount?: number; // or `total`
  // in the future, if needed, we could add:
  // type: 'notebook' | 'console'
}
```

What do you think?

**Comment by firai** [comment]
Thanks for the suggestion, @krassowski! After implementing this, `_modifyEdgeNavigation()` seems to be broken for the first cell on JL reload, but everything works after jumping to another cell and back. This bug doesn't seem to exist at commit `0e00f0ffff0510ba4eb1655969b5528acfc135f0` (before I implement the interface). I see the following browser console error, but it doesn't seem to be related, as I get the same error with the commit before the interface. Do you have any suggestions on how to debug this?

<details>

```
Uncaught (in promise) TypeError: e is undefined
    Pe http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    r http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    r http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    c http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    m http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    l http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    emit http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    _onCellInViewportChanged http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    m http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    l http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    emit http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    set inViewport http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    attachWidget http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    insertWidget http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    _updateForDeferMode http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    _runOnIdleTime http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    _runOnIdleTime http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    onUpdateRequest http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    onUpdateRequest http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    processMessage http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    b http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    o http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    w http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    n http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    promise callback*37192/n http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    y http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    r http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    update http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    m http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    l http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    emit http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    _triggerChange http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    _onModelChanged http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    m http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    l http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    emit http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    onModelContentChanged http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    m http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    l http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    emit http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    triggerContentChange http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    _onCellsChanged http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    m http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    l http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    emit http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    _onSharedModelChanged http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    _onSharedModelChanged http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    m http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    l http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    emit http://127.0.0.1:8888/static/lab/jlab_core.be6103fe6f6cc2c18378.js?v=be6103fe6f6cc2c18378:1
    _onYCellsChanged http://127.0.0.1:8888/static/lab/1168.e4d38ba5d2b37479ba8a.js?v=e4d38ba5d2b37479ba8a:1
    r http://127.0.0.1:8888/static/lab/383.db345dbeef5ef774e50c.js?v=db345dbeef5ef774e50c:1
    ji http://127.0.0.1:8888/static/lab/383.db345dbeef5ef774e50c.js?v=db345dbeef5ef774e50c:1
jlab_core.be6103fe6f6cc2c18378.js:1:1124981
```
</details>

**Comment by firai** [comment]
Completely scratching my head on this one, and I'm starting to think this might be related to https://github.com/jupyterlab-contrib/jupyterlab-vim/issues/15#issuecomment-1711856628.

`modifyCell()` and `_modifyEdgeNavigation()` get called several times when JL is loaded, but when this bug happens, there's somehow an extra `modifyEditor()` at the end. Seems to be some sort of race condition, because it will very occasionally work. I don't know why changing to an interface causes the bug to happen more consistently/frequently. Maybe the extra code time is affecting the race condition.

**Comment by firai** [comment]
As it turns out, I was making life difficult for myself. This bug only occurs when there's a file editor in another background tab, and it (probably) has nothing to do with the fact that we changed to using the interface. I think we should be otherwise good to go, pending code review.

**Review by krassowski — APPROVED** [review]
Thank you @firai, tested locally to confirm that this fixes the issue.

**Pull request merged**
