### PR TITLE
Update `codemirror-vim` to 6.2.1 and `jupyterlab` to 4.2.0

### LINKED ISSUE #109: Please respect Jupyterlab settings for non-blinking cursor
Hi.
The blinking cursor in jupyterlab was an issue in the past, see e.g. [here](https://github.com/jupyter/notebook/issues/1570) and [here](https://github.com/jupyterlab/jupyterlab/issues/10443). This was ultimately resolved by providing the user with the ability to set `cursorBlinkRate` to zero.
This also worked with jupyterlab-vim in the past. However, when I again started using it recently, I noticed that the cursor is now blinking again in all browsers, despite the above setting.
Is there a way to make jupyterlab-vim respect the jupyterlab setting, or is there another way to disable cursor blinking?

### PR DESCRIPTION
**Pull request by firai**
# References

Fixes #109, amongst other bug fixes and enhancements in `codemirror-vim` (https://github.com/replit/codemirror-vim/compare/v6.0.14...v6.2.1).

# Code changes

- Bump `codemirror-vim` to 6.2.1.
- Bump `jupyterlab` packages to 4.2.0 to get updated `@codemirror/view` for #109.
- Add guards for possible `null` for `cm.state.vim`, introduced by `codemirror-vim` (https://github.com/replit/codemirror-vim/pull/162).

# Known issues

Not introduced by this PR, but #138 is still broken. JL 4.1, which introduced the new behavior, was already required since #135, so this PR does not (by itself) make the conflict unavoidable.

### CODE REVIEW

**Review by krassowski — APPROVED** [review]
Thank you @firai!

**Comment by firai** [comment]
Hi @krassowski and @ianhi, can either of you help release a new version? It seems like I don't have the permissions to do so. Not sure if it's worth mentioning #138 as a known issue in the release notes.

**Comment by krassowski** [comment]
Not sure if this has to do with your permissions, it failed for me too: https://github.com/jupyterlab-contrib/jupyterlab-vim/actions/runs/10880534712 I think the token has expired, let me set it up for the trusted publishers mechanism

**Comment by krassowski** [comment]
Ok, after https://github.com/jupyterlab-contrib/jupyterlab-vim/pull/147 and a few tweaks in the settings the release came through: https://github.com/jupyterlab-contrib/jupyterlab-vim/releases/tag/v4.1.4 - you should be able to update the release notes manually now :)

**Pull request merged**
