### PR TITLE
TYPO: Update installing.md uninstall command

### PR DESCRIPTION
**Pull request by nikisix**

### CODE REVIEW

**Comment by firai** [comment]
@ianhi @krassowski Should we delete `installing.md` and mention of "JupyterLab <3", i.e. JupyterLab 2, in README altogether? It seems to me that the duplication of information is cause of this typo.

**Comment by krassowski** [comment]
I agree with the idea of deleting it, the less duplication the better.

**Comment by firai** [comment]
Hi @nikisix, thanks for noticing the typo and submitting the PR! Since the extra `installation.md` only exists to provide JL 2 extension instructions and since JL 2 is quite old now, we think it may be best to delete this file altogether. I hope you don't mind us modifying your PR to do so.

**Comment by firai** [comment]
Sorry, I didn't notice that a rebase would be required, which is probably more work than it's worth. I have opened a new PR at #121. Please take a look.

I'll close this PR. Thanks for your contribution!

**Pull request closed without merging**
